import HeroImage from "@/app/components/heroImage";
import DividerMountain from "@/app/components/divider";
import Project from "@/app/components/project";
import Footer from "@/app/components/footer";
import Image from "next/image";

export default function Projets(){
    return (
        <div>
            <HeroImage text={"Canada"} categorie={"Projets"}/>
            <div className="w-full h-[70vw] overflow-hidden relative mt-[-14vw] -mb-40">
                <Image
                    src="/img/uqac.jpg"
                    alt="photo projet picsou"
                    fill
                    sizes="100vw"
                    className="object-cover -mt-[14vw] -z-20"
                />
            </div>

            <div className={"mb-16"}>
                <h1 className={"text-4xl font-black text-black ml-20 mt-10 mb-6"}>Présentation</h1>
                <p className={"mx-20 text-black"}>{"Dans le cadre de mon parcours universitaire, j’ai eu l’opportunité de vivre une année d’échange à l’Université du Québec à Chicoutimi (UQAC). Cette expérience a été bien plus qu’un simple séjour d’études à l’étranger : elle m’a permis de découvrir une nouvelle culture, de sortir de ma zone de confort, et d’élargir mes perspectives aussi bien académiques que personnelles. Située au cœur du Saguenay–Lac-Saint-Jean, la ville de Chicoutimi offre un environnement naturel exceptionnel, propice aux activités de plein air comme la randonnée, le ski ou encore les balades en forêt enneigée. Intégrer une université nord-américaine m’a également permis d’expérimenter une approche pédagogique différente, plus axée sur la participation active, les projets pratiques et le travail collaboratif. Cette année a été marquée par des rencontres enrichissantes, tant avec des étudiants québécois qu’internationaux, et m’a offert une ouverture culturelle et humaine unique, que je considère aujourd’hui comme une étape clé de mon parcours."}</p>
                <h1 className={"text-4xl font-black text-black ml-20 mt-10 mb-6"}>Démarche pour vivre un an au Canada</h1>
                <p className={"mx-20 text-black"}>{"Partir étudier à l’étranger, et en particulier au Canada, demande une préparation rigoureuse en amont. Avant même de pouvoir poser mes valises à Chicoutimi, j’ai dû me renseigner en détail sur les démarches administratives, les retours d’expérience d’anciens étudiants et les conseils pratiques pour bien anticiper cette aventure. La première étape a été de candidater au sein de l'UQAC et d’obtenir une acceptation. Une fois cette étape franchie, j’ai dû entreprendre des démarches spécifiques au Québec : demande de CAQ (Certificat d’acceptation du Québec), puis demande de permis d’études auprès du gouvernement canadien. Cette dernière impliquait aussi un rendez-vous pour la prise des empreintes biométriques, que j’ai réalisé à Lyon. Un autre défi a été de trouver un logement à distance, en évitant les arnaques. Pour cela, j’ai choisi de passer par l’entreprise Logétude, qui propose des logements étudiants fiables à Chicoutimi. Une fois le logement sécurisé, j’ai organisé mon voyage depuis la France, avec un vol jusqu’à Montréal, une nuit en auberge de jeunesse, puis un trajet en bus jusqu’à Chicoutimi le lendemain. Enfin, une fois sur place, il a fallu compléter les démarches administratives locales, notamment pour bénéficier de la RAMQ (Régie de l’assurance maladie du Québec), indispensable pour avoir accès aux soins de santé durant le séjour. Dans mon cas j'étais aussi désireux de travailler sur place afin d'amortir mon voyage et me permettre de visiter ce pays. Pour cela j'ai réaliser les démarches dans le but d'obtenir un Numéro d'Assurance Sociale (NAS). Toutes ces étapes, bien que parfois longues et complexes, ont fait partie intégrante de l’expérience. Elles m’ont permis de gagner en autonomie, en organisation, et m’ont préparé concrètement à vivre cette aventure unique de l’autre côté de l’Atlantique."}</p>
                <h1 className={"text-4xl font-black text-black ml-20 mt-10 mb-6"}>La vie étudiante au Saguenay</h1>
                <p className={"mx-20 text-black"}>{"Vivre au Saguenay, et plus précisément à Chicoutimi, c’est aussi faire l’expérience d’une région magnifique mais qui est très étendue et peu desservie par les transports en commun. Très vite, j’ai réalisé qu’il était presque indispensable d’avoir une voiture pour pouvoir se déplacer librement : faire les courses, aller travailler, explorer les environs… J’ai donc dû effectuer les démarches pour trouver et acheter un véhicule, en consultant des plateformes locales et en restant vigilant face aux éventuelles arnaques. Une fois la voiture achetée, il m’a fallu souscrire à une assurance auto québécoise, différente des modèles européens, et apprendre à conduire dans des conditions hivernales parfois extrêmes. La mécnique est aussi différentes de ce que l'on trouve en France. A cause des hivers glaciales, la rouille attaque beaucoup plus les véhicule il est donc necessaire de réaliser un entretient plus poussé de sa voiture. En raison des températures qui peuvent aussi descendre très bas il est aussi nécessaire d'avoir de l'équipement supplémentaire tel qu'un booster pour réussir à démarrer par un matin à -36°C. Les types de vehicules sont aussi différents et l'on comprend vite pourquoi une 4x4 n'est pas un luxe mais une réelle necessité sur des routes enneigées. Comme la vie sur place peut être coûteuse, il a également été nécessaire pour moi de travailler en parallèle de mes études. J’ai eu l’opportunité de travailler pendant six mois chez Tim Hortons, une célèbre chaîne de cafés et de restauration rapide canadienne. Cette expérience m’a permis de m’intégrer davantage à la culture locale, mais aussi de gagner un revenu pour couvrir une partie de mes frais. Si le rythme de travail était parfois exigeant, surtout combiné aux études, ce job m’a appris la rigueur, la gestion du temps, et m’a permis de rencontrer des Québécois dans un cadre différent de l’université. Enfin, sur le plan académique, j’ai constaté plusieurs différences entre l’UQAC et un IUT français. Les cours sont souvent plus participatifs, avec une place importante accordée aux travaux en équipe, aux présentations orales et aux projets concrets. L’approche pédagogique québécoise est plus souple sur certains aspects, mais elle demande une autonomie importante et une réelle implication dans les travaux à remettre. Cela m’a permis de développer d’autres compétences, notamment en communication et en gestion de projet, tout en m’adaptant à une autre manière d’apprendre."}</p>
                <h1 className={"text-4xl font-black text-black ml-20 mt-10 mb-6"}>Les activités, les paysages et les rencontres</h1>
                <p className={"mx-20 text-black"}>{"Mon année à l’UQAC a été riche en rencontres humaines et en découvertes culturelles. J’ai principalement partagé mon quotidien avec des étudiants français et belges, grâce à ma colocation et aux colocations voisines. Mais j’ai aussi eu la chance de tisser des liens avec des Québécois et des étudiants venus d’autres régions du monde, notamment grâce à mon travail chez Tim Hortons, où la diversité culturelle est grande et les échanges fréquents. Les activités en plein air ont occupé une place centrale dans mon expérience. J’ai profité pleinement des randonnées en automne et au printemps, appréciant les paysages qui se transforment au fil des saisons. Les balades en raquettes ont aussi été l’occasion de découvrir la nature sous un autre angle, au cœur des forêts enneigées. Mais c’est surtout le ski, aussi bien de piste qu’en ski de randonnée, qui m’a vraiment marqué, notamment dans les stations du Valinouët et du Mont Édouard, où les conditions sont idéales et les paysages à couper le souffle. Le Québec est un territoire aux saisons très marquées : l’été apporte chaleur et journées longues, l’automne peint les forêts de rouge et d’or, tandis que l’hiver impose son froid rigoureux et une épaisse couverture de neige. Ces changements accentuent la beauté spectaculaire des paysages et renforcent le lien avec la nature, si présent dans la vie locale. Enfin, j’ai eu la chance de voyager et de découvrir plusieurs régions emblématiques du Québec et du Canada : Tadoussac et son célèbre fjord, la ville historique de Québec, le vaste Lac Saint-Jean, ainsi que les métropoles culturelles et politiques de Montréal et Ottawa. Ces escapades ont complété mon immersion et m’ont permis d’apprécier la richesse et la diversité du pays."}</p>
                <h1 className={"text-4xl font-black text-black ml-20 mt-10 mb-6"}>Conclusion</h1>
                <p className={"mx-20 text-black"}>{"Cette année passée à l’UQAC et au Québec a été bien plus qu’une simple expérience académique. Elle m’a permis de développer des compétences solides et variées, tant sur le plan personnel que professionnel. Travailler six mois chez Tim Hortons a été un véritable défi et un moteur d’apprentissage. J’y ai appris à gérer une équipe composée de personnes aux cultures et aux âges très divers, tout en maintenant un bon esprit d’équipe et une qualité constante dans le service. Cette expérience m’a renforcé dans mes capacités de communication, d’adaptabilité et de gestion du stress dans un environnement dynamique. Au-delà du travail, vivre à l’étranger m’a également donné l’occasion de gagner en autonomie, de mieux organiser mon temps entre études, emploi et loisirs, et d’apprendre à m’adapter à de nouvelles méthodes pédagogiques et modes de vie. J’ai renforcé mon sens de la collaboration en travaillant avec des étudiants internationaux sur des projets concrets. En somme, ce séjour a été un véritable tremplin pour mon développement professionnel et personnel. Il m’a permis d’élargir mes horizons, d’affiner mes compétences interpersonnelles et organisationnelles, et de me préparer à relever avec confiance les futurs défis de ma carrière."}</p>
            </div>
            <DividerMountain rotation={-180}/>
            <div className={"bg-customBlue px-20 mt-[-5px] py-10"}>
                <h1 className={"text-white font-black text-4xl pb-10"}>Mes autres projets</h1>
                <div className={"flex justify-around items-center"}>
                    <Project nom={"Picsou"} srcImage={"picsou.svg"} resume={"Projet stage en duo visant à la réalisation d'une application de gestion de dépenses au sein d'un groupe"}/>
                    <Project nom={"Terraforma"} srcImage={"terra.jpg"} resume={"Par équipe de 7, nous avons réaliser un serious game afin d'ameliorer le niveau de classes de 3ème en SVT"}/>
                </div>
            </div>
            <Footer/>
        </div>
    )
}